// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelApi.Models;

#nullable disable

namespace TravelApi.Migrations
{
    [DbContext(typeof(TravelApiContext))]
    partial class TravelApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelApi.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("PublicTransit")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Walkability")
                        .HasColumnType("int");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Country = "United States",
                            Description = "Modern, walkable city known for its food and beer culture",
                            Name = "Portland",
                            PublicTransit = 4,
                            Rating = 5,
                            Walkability = 5
                        },
                        new
                        {
                            LocationId = 2,
                            Country = "United States",
                            Description = "Like Portland, but not as cool. Thinks it invented soccer.",
                            Name = "Seattle",
                            PublicTransit = 4,
                            Rating = 4,
                            Walkability = 3
                        },
                        new
                        {
                            LocationId = 3,
                            Country = "Germany",
                            Description = "The apex of human culture",
                            Name = "Berlin",
                            PublicTransit = 5,
                            Rating = 5,
                            Walkability = 5
                        },
                        new
                        {
                            LocationId = 4,
                            Country = "UK",
                            Description = "Fish n' chips, innit",
                            Name = "London",
                            PublicTransit = 3,
                            Rating = 5,
                            Walkability = 5
                        },
                        new
                        {
                            LocationId = 5,
                            Country = "United States",
                            Description = "Really hot weather and hotter beaches",
                            Name = "Miami",
                            PublicTransit = 1,
                            Rating = 3,
                            Walkability = 2
                        },
                        new
                        {
                            LocationId = 6,
                            Country = "United States",
                            Description = "trust me, just don't",
                            Name = "Cleveland",
                            PublicTransit = 1,
                            Rating = 1,
                            Walkability = 1
                        },
                        new
                        {
                            LocationId = 7,
                            Country = "Japan",
                            Description = "Lots of people, little space",
                            Name = "Tokyo",
                            PublicTransit = 5,
                            Rating = 4,
                            Walkability = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
